...........................................................
DATA SEGMENT 
PATH DB "D:\DIRECT1\NEWDIR",0       ;ASCIIZ string for path 
        ......................
DATA ENDS 
..........................................................................
CODE SEGMENT 
            mov ax,DATA             ;base address
            mov ds,ax               ;of data segment 
            lea dx,PATH             ;DS:DX - address of the path string 
            mov ah,3Ah              ;function 3Ah - delete subdirectory 
            int 21h                 ;call MS-DOS service
            jc error                ;error, if carry flag = 1 
            ...................................
 CODE ENDS 
 ..........................................................................
